services:
  - type: web
    name: benin-luxe-cajou-api
    runtime: python         # CORRIGÉ: 'runtime' est la propriété correcte, pas 'env'.
    plan: free              # Il est bon de spécifier le plan (ex: free, starter)
    buildCommand: "./build.sh"
    startCommand: "gunicorn run:app"
    envVars:
      # --- On ne fait PAS référence à une base Render ---
      # Ces variables seront ajoutées manuellement dans l'interface de Render.
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true # On laisse Render générer une clé sécurisée
      - key: CLOUDINARY_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
      # --- Variables pour l'envoi d'email ---
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USE_TLS
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false